PUT http://localhost:3001/api/blogs/649864552b40866c8659e3fd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRUZXN0YWFqYSIsImlkIjoiNjQ5ODUyNWYzYmJjNGFkNjNjNmJhM2U3IiwiaWF0IjoxNjg3Nzk2NTQ3fQ.w4JZiU6jieBpFo7fI1GBJpUdAQppoR4ttAEoz7bj--Y

{
    "author": "teemu testaaja",
    "title": "Muokattu testikirja",
    "likes": 12345,
    "url": "testi.fi/testipro"
}