post http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRUZXN0YWFqYSIsImlkIjoiNjQ5ODUyNWYzYmJjNGFkNjNjNmJhM2U3IiwiaWF0IjoxNjg3NzEzNTMwfQ.Pr734f5VxnmW13ynr21Po2uDXBbY1MSuRFvG2aOu8cI

{
    "author": "teemu testaaja",
    "title": "testi pt2",
    "likes": 123,
    "url": "testi.fi"
}